package ir.pchas.tayehclient.model.user

import ir.pchas.tayehclient.model.*
import ir.pchas.tayehclient.model.shop.*
import java.util.*

public data class User(
    val id: Int,
    val name: String,
    val sex: Sex,
    val description: String,
    val idCard: String,
    val father: String,
    val birthdate: String,
    val addresses: List<Address>,
    val phone: String,
    val mobile: String,
    val email: String,
    val website: String,
    val referentId: Int,
    val provinceId: Int,
    val province: Province,
    val cityId: Int,
    val city: City,
    val subUserOf: List<SubUser>,
    val customersCreated: List<Customer>,
    val subUsersCreated: List<SubUser>,
    val subscriptions: List<Subscription>,
    val payments: List<Payment>,
    val instances: List<Instance>,
    val myInstances: List<Instance>,
    val myInstancesCount: Int,
    val primaryInstanceId: Int,
    val primaryInstance: Instance,
    val reminders: List<Reminder>,
    val isVerified: Boolean,
    val socket: String,
    val imageId: Int,
    val image: Media,
    val uploads: List<Media>,
    val generatedInvoices: List<Invoice>,
    val createdProducts: List<Product>,
    val online: Boolean,
    val lastOnline: Date,
    val role: UserRole,
    val isDeveloper: Boolean,
    val deleted: Boolean,
    val dateCreated: Date,
    val dateUpdated: Date,
    val dateDeleted: Date,
)